/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackCard: typeof import('./src/components/storageUI/Card/BackCard.vue')['default']
    Badge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    BoxCard: typeof import('./src/components/storageUI/Card/BoxCard.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    BwChar: typeof import('./src/components/storageUI/Chart/BwChar.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    DashboardHeader: typeof import('./src/components/storageUI/Header/DashboardHeader.vue')['default']
    IMdiBrightness4: typeof import('~icons/mdi/brightness4')['default']
    IMdiBrightness7: typeof import('~icons/mdi/brightness7')['default']
    IMdiTimerSand: typeof import('~icons/mdi/timer-sand')['default']
    IMdiUpload: typeof import('~icons/mdi/upload')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    IRiClipboardLine: typeof import('~icons/ri/clipboard-line')['default']
    IRiExternalLinkFill: typeof import('~icons/ri/external-link-fill')['default']
    IRiFileList3Line: typeof import('~icons/ri/file-list3-line')['default']
    IRiLinkM: typeof import('~icons/ri/link-m')['default']
    IRiLinkUnlinkM: typeof import('~icons/ri/link-unlink-m')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/ui/scroll-area/ScrollBar.vue')['default']
    SearchCard: typeof import('./src/components/storageUI/Card/SearchCard.vue')['default']
    SearchInput: typeof import('./src/components/storageUI/Input/SearchInput.vue')['default']
    UploadCard: typeof import('./src/components/storageUI/Card/UploadCard.vue')['default']
    UploadLoading: typeof import('./src/components/storageUI/Loading/UploadLoading.vue')['default']
  }
}
